spring:
  application:
    name: country-service
server:
  port: ${PORT:8081}
  servlet:
    context-path: /cservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

