spring:
  application:
    name: country-service
server:
  port: ${PORT:8081}
  servlet:
    context-path: /cservice

eureka:
  client:
    serviceUrl:
      defaultZone: https://lwl-ds-service.herokuapp.com/eureka/

